services:
  postgres:
    image: postgres:17-alpine
    container_name: demo-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dev
    ports:
      - "5432:5432"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: demo-jaeger
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "16686:16686" # Jaeger UI
