spring:
    application:
        name: Weblap

    datasource:
        url: ${DB_URI:jdbc:postgresql://localhost:5432/dev}
        username: ${DB_USER:postgres}
        password: ${DB_PASS:postgres}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    liquibase:
        change-log: classpath:database/master.xml

jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

springdoc:
    api-docs:
        path: /api/openapi
    swagger-ui:
        layout: BaseLayout
        path: /api/swagger
        url: /api/openapi.yaml

management:
    tracing:
        sampling:
            probability: 1.0
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: '*'
    server:
        port: ${MANAGEMENT_PORT:8081}
server:
    port: ${SERVER_PORT:8081}
