server:
  port: ${SERVER_PORT:8080}

spring:
  web:
    resources:
      static-locations: "classpath:file:/app/javadoc/,file:/app/openapi/"
  application:
    name: File Search
  datasource:
    url: ${DB_URI:jdbc:postgresql://localhost:5432/dev}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    change-log: classpath:database/master.xml